name: ping_backend
run-name: Pinging backend aliveness
on:
  schedule:
    - cron: '44 10 * * 0,4'
  workflow_dispatch:
    
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - run: curl ${{secrets.SUPABASE_ENDPOINT}} -H 'apikey:${{secrets.SUPABASE_ANON_KEY}}'