name: ping_backend
run-name: Pinging backend aliveness
on:
  schedule:
    - cron: '44 10 * * 0,4'
  workflow_dispatch:
    
jobs:
  curl:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ENDPOINT: ${{secrets.SUPABASE_ENDPOINT}}
      SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
    steps:
    - run: curl "$SUPABASE_ENDPOINT" -H "apikey:$SUPABASE_ANON_KEY"