name: process_data
run-name: Processing HDB and Private Residential Data
on:
  schedule:
    - cron: '22 10 * * 6' # every sat 10:22am
  workflow_dispatch:
    
jobs:
  ETL:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      SUPABASE_ENDPOINT: ${{secrets.SUPABASE_ENDPOINT}}
      SUPABASE_SERVICE_KEY: ${{secrets.SUPABASE_SERVICE_KEY}}
      URA_ACCESS_KEY: ${{secrets.URA_ACCESS_KEY}}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: sg_housing_database
        environment-file: environment.prod.yml
        python-version: 3.7
        auto-activate-base: false
    - run: |
        conda info
        conda list
    - run:
        python main.py